import { EntityDef as Modi } from "./Modi/Schema";
import { EntityDef as ModiEntity } from "./ModiEntity/Schema";
import { EntityDef as Oper } from "./Oper/Schema";
import { EntityDef as OperEntity } from "./OperEntity/Schema";
import { EntityDef as Address } from "./Address/Schema";
import { EntityDef as Application } from "./Application/Schema";
import { EntityDef as Area } from "./Area/Schema";
import { EntityDef as Captcha } from "./Captcha/Schema";
import { EntityDef as Domain } from "./Domain/Schema";
import { EntityDef as Email } from "./Email/Schema";
import { EntityDef as ExtraFile } from "./ExtraFile/Schema";
import { EntityDef as Mobile } from "./Mobile/Schema";
import { EntityDef as UserRole } from "./UserRole/Schema";
import { EntityDef as Role } from "./Role/Schema";
import { EntityDef as UserSystem } from "./UserSystem/Schema";
import { EntityDef as System } from "./System/Schema";
import { EntityDef as Token } from "./Token/Schema";
import { EntityDef as User } from "./User/Schema";
import { EntityDef as UserEntityGrant } from "./UserEntityGrant/Schema";
import { EntityDef as WechatQrCode } from "./WechatQrCode/Schema";
import { EntityDef as WechatUser } from "./WechatUser/Schema";
export declare type EntityDict = {
    modi: Modi;
    modiEntity: ModiEntity;
    oper: Oper;
    operEntity: OperEntity;
    address: Address;
    application: Application;
    area: Area;
    captcha: Captcha;
    domain: Domain;
    email: Email;
    extraFile: ExtraFile;
    mobile: Mobile;
    userRole: UserRole;
    role: Role;
    userSystem: UserSystem;
    system: System;
    token: Token;
    user: User;
    userEntityGrant: UserEntityGrant;
    wechatQrCode: WechatQrCode;
    wechatUser: WechatUser;
};
