import { EntityDef as Address } from "./Address/Schema";
import { EntityDef as Application } from "./Application/Schema";
import { EntityDef as Area } from "./Area/Schema";
import { EntityDef as ExtraFile } from "./ExtraFile/Schema";
import { EntityDef as Mobile } from "./Mobile/Schema";
import { EntityDef as UserRole } from "./UserRole/Schema";
import { EntityDef as Role } from "./Role/Schema";
import { EntityDef as UserSystem } from "./UserSystem/Schema";
import { EntityDef as System } from "./System/Schema";
import { EntityDef as Token } from "./Token/Schema";
import { EntityDef as User } from "./User/Schema";
import { EntityDef as UserEntityGrant } from "./UserEntityGrant/Schema";
import { EntityDef as WechatQrCode } from "./WechatQrCode/Schema";
import { EntityDef as WechatUser } from "./WechatUser/Schema";
export declare type EntityDict = {
    address: Address;
    application: Application;
    area: Area;
    extraFile: ExtraFile;
    mobile: Mobile;
    userRole: UserRole;
    role: Role;
    userSystem: UserSystem;
    system: System;
    token: Token;
    user: User;
    userEntityGrant: UserEntityGrant;
    wechatQrCode: WechatQrCode;
    wechatUser: WechatUser;
};
