import { String, Text, Datetime, Image, PrimaryKey, ForeignKey } from "oak-domain/lib/types/DataType";
import { Q_DateValue, Q_StringValue, Q_EnumValue, NodeId, MakeFilter, FulltextFilter, ExprOp, ExpressionKey } from "oak-domain/lib/types/Demand";
import { OneOf } from "oak-domain/lib/types/Polyfill";
import * as SubQuery from "../_SubQuery";
import { FormCreateData, FormUpdateData, Operation as OakOperation } from "oak-domain/lib/types/Entity";
import { UserState, IdState, ParticularAction, Action } from "./Action";
import * as Mobile from "../Mobile/Schema";
import * as UserRole from "../UserRole/Schema";
import * as UserSystem from "../UserSystem/Schema";
import * as Token from "../Token/Schema";
import * as WechatUser from "../WechatUser/Schema";
import * as ExtraFile from "../ExtraFile/Schema";
export declare type OpSchema = {
    id: PrimaryKey;
    $$createAt$$: Datetime;
    $$updateAt$$: Datetime;
    $$removeAt$$?: Datetime | null;
    name: String<16>;
    nickname?: String<64> | null;
    password?: Text | null;
    birth?: Datetime | null;
    gender?: ('male' | 'female') | null;
    avatar?: Image | null;
    idCardType?: ('ID-Card' | 'passport' | 'Mainland-passport') | null;
    idNumber?: String<32> | null;
    refId?: ForeignKey<"user"> | null;
    userState?: UserState | null;
    idState?: IdState | null;
};
export declare type OpAttr = keyof OpSchema;
export declare type Schema = {
    id: PrimaryKey;
    $$createAt$$: Datetime;
    $$updateAt$$: Datetime;
    $$removeAt$$?: Datetime | null;
    name: String<16>;
    nickname?: String<64> | null;
    password?: Text | null;
    birth?: Datetime | null;
    gender?: ('male' | 'female') | null;
    avatar?: Image | null;
    idCardType?: ('ID-Card' | 'passport' | 'Mainland-passport') | null;
    idNumber?: String<32> | null;
    refId?: ForeignKey<"user"> | null;
    userState?: UserState | null;
    idState?: IdState | null;
    ref?: Schema | null;
    mobile$user?: Array<Mobile.Schema>;
    userRole$user?: Array<UserRole.Schema>;
    userSystem$user?: Array<UserSystem.Schema>;
    token$user?: Array<Token.Schema>;
    token$player?: Array<Token.Schema>;
    user$ref?: Array<Schema>;
    wechatUser$user?: Array<WechatUser.Schema>;
    extraFile$entity?: Array<ExtraFile.Schema>;
} & {
    [A in ExpressionKey]?: any;
};
declare type AttrFilter = {
    id: Q_StringValue | SubQuery.UserIdSubQuery;
    $$createAt$$: Q_DateValue;
    $$updateAt$$: Q_DateValue;
    name: Q_StringValue;
    nickname: Q_StringValue;
    password: Q_StringValue;
    birth: Q_DateValue;
    gender: Q_EnumValue<'male' | 'female'>;
    avatar: Q_StringValue;
    idCardType: Q_EnumValue<'ID-Card' | 'passport' | 'Mainland-passport'>;
    idNumber: Q_StringValue;
    refId: Q_StringValue | SubQuery.UserIdSubQuery;
    ref: Filter;
    userState: Q_EnumValue<UserState>;
    idState: Q_EnumValue<IdState>;
};
export declare type Filter = MakeFilter<AttrFilter & ExprOp<OpAttr> & FulltextFilter>;
export declare type Projection = {
    "#id"?: NodeId;
    [k: string]: any;
    id: 1;
    $$createAt$$?: 1;
    $$updateAt$$?: 1;
    name?: 1;
    nickname?: 1;
    password?: 1;
    birth?: 1;
    gender?: 1;
    avatar?: 1;
    idCardType?: 1;
    idNumber?: 1;
    refId?: 1;
    ref?: Projection;
    userState?: 1;
    idState?: 1;
    mobile$user?: Mobile.Selection;
    userRole$user?: UserRole.Selection;
    userSystem$user?: UserSystem.Selection;
    token$user?: Token.Selection;
    token$player?: Token.Selection;
    user$ref?: Selection;
    wechatUser$user?: WechatUser.Selection;
    extraFile$entity?: ExtraFile.Selection;
} & Partial<ExprOp<OpAttr>>;
export declare type ExportProjection = {
    "#id"?: NodeId;
    [k: string]: any;
    id?: string;
    $$createAt$$?: string;
    $$updateAt$$?: string;
    name?: string;
    nickname?: string;
    password?: string;
    birth?: string;
    gender?: string;
    avatar?: string;
    idCardType?: string;
    idNumber?: string;
    refId?: string;
    ref?: ExportProjection;
    userState?: string;
    idState?: string;
    mobile$user?: Mobile.Exportation;
    userRole$user?: UserRole.Exportation;
    userSystem$user?: UserSystem.Exportation;
    token$user?: Token.Exportation;
    token$player?: Token.Exportation;
    user$ref?: Exportation;
    wechatUser$user?: WechatUser.Exportation;
    extraFile$entity?: ExtraFile.Exportation;
} & Partial<ExprOp<OpAttr>>;
declare type UserIdProjection = OneOf<{
    id: 1;
    refId: 1;
}>;
export declare type SortAttr = OneOf<{
    id: 1;
    $$createAt$$: 1;
    $$updateAt$$: 1;
    name: 1;
    nickname: 1;
    password: 1;
    birth: 1;
    gender: 1;
    avatar: 1;
    idCardType: 1;
    idNumber: 1;
    refId: 1;
    ref: SortAttr;
    userState: 1;
    idState: 1;
} & ExprOp<OpAttr>>;
export declare type SortNode = {
    $attr: SortAttr;
    $direction?: "asc" | "desc";
};
export declare type Sorter = SortNode[];
export declare type SelectOperation<P = Projection> = OakOperation<"select", P, Filter, Sorter>;
export declare type Selection<P = Projection> = Omit<SelectOperation<P>, "action">;
export declare type Exportation = OakOperation<"export", ExportProjection, Filter, Sorter>;
export declare type CreateOperationData = FormCreateData<Omit<OpSchema, "refId" | "ref"> & ({
    ref?: CreateSingleOperation | (UpdateOperation & {
        id: String<64>;
    });
    refId?: undefined;
} | {
    ref?: undefined;
    refId?: String<64>;
}) & {
    [k: string]: any;
    mobile$user?: Mobile.CreateOperation | Mobile.UpdateOperation;
    userRole$user?: UserRole.CreateOperation | UserRole.UpdateOperation;
    userSystem$user?: UserSystem.CreateOperation | UserSystem.UpdateOperation;
    token$user?: Token.CreateOperation | Token.UpdateOperation;
    token$player?: Token.CreateOperation | Token.UpdateOperation;
    user$ref?: CreateOperation | UpdateOperation;
    wechatUser$user?: WechatUser.CreateOperation | WechatUser.UpdateOperation;
    extraFile$entity?: ExtraFile.CreateOperation | ExtraFile.UpdateOperation;
}>;
export declare type CreateSingleOperation = OakOperation<"create", CreateOperationData>;
export declare type CreateMultipleOperation = OakOperation<"create", Array<CreateOperationData>>;
export declare type CreateOperation = CreateSingleOperation | CreateMultipleOperation;
export declare type UpdateOperationData = FormUpdateData<Omit<OpSchema, "refId" | "ref">> & ({
    ref?: CreateSingleOperation | Omit<UpdateOperation, "id" | "ids" | "filter">;
    refId?: undefined;
} | {
    ref?: undefined;
    refId?: String<64>;
}) & {
    [k: string]: any;
    mobiles$user?: Mobile.CreateOperation | Omit<Mobile.UpdateOperation, "id" | "ids" | "filter">;
    userRoles$user?: UserRole.CreateOperation | Omit<UserRole.UpdateOperation, "id" | "ids" | "filter">;
    userSystems$user?: UserSystem.CreateOperation | Omit<UserSystem.UpdateOperation, "id" | "ids" | "filter">;
    tokens$user?: Token.CreateOperation | Omit<Token.UpdateOperation, "id" | "ids" | "filter">;
    tokens$player?: Token.CreateOperation | Omit<Token.UpdateOperation, "id" | "ids" | "filter">;
    users$ref?: CreateOperation | Omit<UpdateOperation, "id" | "ids" | "filter">;
    wechatUsers$user?: WechatUser.CreateOperation | Omit<WechatUser.UpdateOperation, "id" | "ids" | "filter">;
    extraFiles$entity?: ExtraFile.CreateOperation | Omit<ExtraFile.UpdateOperation, "id" | "ids" | "filter">;
};
export declare type UpdateOperation = OakOperation<ParticularAction | "update", UpdateOperationData, Filter>;
export declare type RemoveOperationData = {} & {
    ref?: Omit<UpdateOperation | RemoveOperation, "id" | "ids" | "filter">;
} & {
    [k: string]: any;
    mobiles$user?: Omit<Mobile.UpdateOperation | Mobile.RemoveOperation, "id" | "ids" | "filter">;
    userRoles$user?: Omit<UserRole.UpdateOperation | UserRole.RemoveOperation, "id" | "ids" | "filter">;
    userSystems$user?: Omit<UserSystem.UpdateOperation | UserSystem.RemoveOperation, "id" | "ids" | "filter">;
    tokens$user?: Omit<Token.UpdateOperation | Token.RemoveOperation, "id" | "ids" | "filter">;
    tokens$player?: Omit<Token.UpdateOperation | Token.RemoveOperation, "id" | "ids" | "filter">;
    users$ref?: Omit<UpdateOperation | RemoveOperation, "id" | "ids" | "filter">;
    wechatUsers$user?: Omit<WechatUser.UpdateOperation | WechatUser.RemoveOperation, "id" | "ids" | "filter">;
    extraFiles$entity?: Omit<ExtraFile.UpdateOperation | ExtraFile.RemoveOperation, "id" | "ids" | "filter">;
};
export declare type RemoveOperation = OakOperation<"remove", RemoveOperationData, Filter>;
export declare type Operation = CreateOperation | UpdateOperation | RemoveOperation | SelectOperation;
export declare type UserIdSubQuery = Selection<UserIdProjection>;
export declare type NativeAttr = OpAttr | `ref.${OpAttr}` | `ref.ref.${OpAttr}` | `ref.ref.ref.${OpAttr}`;
export declare type FullAttr = NativeAttr | `mobiles$${number}.${Mobile.NativeAttr}` | `userRoles$${number}.${UserRole.NativeAttr}` | `userSystems$${number}.${UserSystem.NativeAttr}` | `tokens$user$${number}.${Token.NativeAttr}` | `tokens$player$${number}.${Token.NativeAttr}` | `users$${number}.${NativeAttr}` | `wechatUsers$${number}.${WechatUser.NativeAttr}` | `extraFiles$${number}.${ExtraFile.NativeAttr}`;
export declare type EntityDef = {
    Schema: Schema;
    OpSchema: OpSchema;
    Action: Action;
    Selection: Selection;
    Operation: Operation;
    ParticularAction: ParticularAction;
};
export {};
