import * as React from 'react';
import { Form, Input, Radio, Checkbox, Button, Switch, MessagePlugin, DatePicker, Tooltip, CheckboxGroup } from 'tdesign-react';

const { FormItem } = Form;
export default function render() {
    const { name, mobile } = this.state;
    return (
        <div>
           <Form
                colon={false}
                labelAlign="right"
                labelWidth="100px"
                layout="vertical"
                preventSubmitDefault
                resetType="empty"
                showErrorMessage
                submitWithWarningMessage={false}
                >
                <FormItem
                    label="姓名"
                    name="name"
                    successBorder={false}
                >
                    <Input
                        onChange={(value, context) => {
                            this.setUpdateData('name', value);
                        }}
                        value={name}
                        align="left"
                        autoWidth={false}
                        autofocus={false}
                        clearable={false}
                        defaultValue=""
                        placeholder="请输入内容"
                        readonly={false}
                        showClearIconOnEmpty={false}
                        size="medium"
                        status="default"
                        type="text"
                    />
                </FormItem>
                <FormItem
                    label="手机号码"
                    name="mobile"
                    successBorder={false}
                >
                    <Input
                        value={mobile}
                        align="left"
                        autoWidth={false}
                        autofocus={false}
                        clearable={false}
                        defaultValue=""
                        placeholder="请输入内容"
                        readonly={false}
                        showClearIconOnEmpty={false}
                        size="medium"
                        status="default"
                        type="text"
                    />
                </FormItem>
                <FormItem
                    initialData={[
                    '1'
                    ]}
                    label="课程"
                    name="course"
                    successBorder={false}
                >
                <Checkbox.Group
                    defaultValue={[]}
                    max={undefined}
                    >
                    <Checkbox
                        checkAll={false}
                        defaultChecked={false}
                        disabled={undefined}
                        indeterminate={false}
                        readonly={false}
                        value="1"
                    >
                        语文
                    </Checkbox>
                    <Checkbox
                        checkAll={false}
                        defaultChecked={false}
                        disabled={undefined}
                        indeterminate={false}
                        readonly={false}
                        value="2"
                    >
                        数学
                    </Checkbox>
                    <Checkbox
                        checkAll={false}
                        defaultChecked={false}
                        disabled={undefined}
                        indeterminate={false}
                        readonly={false}
                        value="3"
                    >
                        英语
                    </Checkbox>
                    <Checkbox
                        checkAll={false}
                        defaultChecked={false}
                        disabled={undefined}
                        indeterminate={false}
                        readonly={false}
                        value="4"
                    >
                        体育
                    </Checkbox>
                    </Checkbox.Group>
                </FormItem>
            </Form>
        </div>
    );
}