"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var address_1 = tslib_1.__importDefault(require("./address"));
var user_1 = tslib_1.__importDefault(require("./user"));
var userEntityGrant_1 = tslib_1.__importDefault(require("./userEntityGrant"));
var wechatQrCode_1 = tslib_1.__importDefault(require("./wechatQrCode"));
var message_1 = tslib_1.__importDefault(require("./message"));
var notification_1 = tslib_1.__importDefault(require("./notification"));
var wechatLogin_1 = tslib_1.__importDefault(require("./wechatLogin"));
var application_1 = tslib_1.__importDefault(require("./application"));
var articleMenu_1 = tslib_1.__importDefault(require("./articleMenu"));
var article_1 = tslib_1.__importDefault(require("./article"));
exports.default = tslib_1.__spreadArray(tslib_1.__spreadArray(tslib_1.__spreadArray(tslib_1.__spreadArray(tslib_1.__spreadArray(tslib_1.__spreadArray(tslib_1.__spreadArray(tslib_1.__spreadArray(tslib_1.__spreadArray(tslib_1.__spreadArray([], tslib_1.__read(application_1.default), false), tslib_1.__read(address_1.default), false), tslib_1.__read(user_1.default), false), tslib_1.__read(userEntityGrant_1.default), false), tslib_1.__read(wechatQrCode_1.default), false), tslib_1.__read(message_1.default), false), tslib_1.__read(notification_1.default), false), tslib_1.__read(wechatLogin_1.default), false), tslib_1.__read(articleMenu_1.default), false), tslib_1.__read(article_1.default), false);
