"use strict";
// import { registerMessageNotificationConverters } from './triggers/message';
// import { registerWeChatPublicEventCallback } from './endpoints';
Object.defineProperty(exports, "__esModule", { value: true });
exports.updateFreeDict = exports.authDeduceRelationMap = exports.selectFreeEntities = exports.FrontendRuntimeContext = exports.BackendRuntimeContext = void 0;
const tslib_1 = require("tslib");
tslib_1.__exportStar(require("./types/Exception"), exports);
tslib_1.__exportStar(require("./types/Page"), exports);
tslib_1.__exportStar(require("./types/Message"), exports);
tslib_1.__exportStar(require("./types/RuntimeCxt"), exports);
// export { getLivestream, getPlayBackUrl, getStreamObj } from './utils/livestream';
var BackendRuntimeContext_1 = require("./context/BackendRuntimeContext");
Object.defineProperty(exports, "BackendRuntimeContext", { enumerable: true, get: function () { return BackendRuntimeContext_1.BackendRuntimeContext; } });
var FrontendRuntimeContext_1 = require("./context/FrontendRuntimeContext");
Object.defineProperty(exports, "FrontendRuntimeContext", { enumerable: true, get: function () { return FrontendRuntimeContext_1.FrontendRuntimeContext; } });
// export { registerWechatPublicTags } from './config/constants';
// export { registerCos as registerUploader } from './utils/cos';
var relation_1 = require("./config/relation");
Object.defineProperty(exports, "selectFreeEntities", { enumerable: true, get: function () { return relation_1.selectFreeEntities; } });
Object.defineProperty(exports, "authDeduceRelationMap", { enumerable: true, get: function () { return relation_1.authDeduceRelationMap; } });
Object.defineProperty(exports, "updateFreeDict", { enumerable: true, get: function () { return relation_1.updateFreeDict; } });
