import { loginByMobile, loginWechat, loginWechatMp, syncUserInfoWechatMp, sendCaptcha, switchTo, refreshWechatPublicUserInfo, getWechatMpUserPhoneNumber, logout, loginByWechat, wakeupParasite } from './token';
import { getUploadInfo, getInfoByUrl } from './extraFile';
import { getApplication, signatureJsSDK } from './application';
import { updateConfig, updateApplicationConfig } from './config';
import { mergeUser } from './user';
import { createWechatLogin } from './wechaLogin';
import { unbindingWechat } from './wechatUser';
declare const aspectDict: {
    mergeUser: typeof mergeUser;
    switchTo: typeof switchTo;
    refreshWechatPublicUserInfo: typeof refreshWechatPublicUserInfo;
    loginByMobile: typeof loginByMobile;
    loginWechat: typeof loginWechat;
    loginWechatMp: typeof loginWechatMp;
    wakeupParasite: typeof wakeupParasite;
    syncUserInfoWechatMp: typeof syncUserInfoWechatMp;
    getUploadInfo: typeof getUploadInfo;
    sendCaptcha: typeof sendCaptcha;
    getApplication: typeof getApplication;
    updateConfig: typeof updateConfig;
    updateApplicationConfig: typeof updateApplicationConfig;
    getWechatMpUserPhoneNumber: typeof getWechatMpUserPhoneNumber;
    logout: typeof logout;
    signatureJsSDK: typeof signatureJsSDK;
    createWechatLogin: typeof createWechatLogin;
    unbindingWechat: typeof unbindingWechat;
    loginByWechat: typeof loginByWechat;
    getInfoByUrl: typeof getInfoByUrl;
};
export default aspectDict;
